### ISSUE TITLE
innxmit should keep the order of replies when streaming

### ISSUE THREAD

**Issue by rra** [InterNetNews/inn#142]
**Reported by iulius on 8 Nov 2009 20:08 UTC**
Programs should not expect a message-ID in every answer of streaming commands (`CHECK`/`TAKETHIS`); they should know to which question the answers refers.

For instance:

```
  CHECK bad id
  501 Syntax error in message-ID
```

The message-ID is not necessarily given in the answer.

`innxmit` will block on such answers.

**Comment by rra** [comment]
**Modified by iulius on 2 Apr 2015 18:51 UTC**

**Comment by rra** [comment]
**Comment by iulius on 31 Jul 2016 20:08 UTC**
Milestone renamed

**Comment by Julien-Elie** [comment]
Fixed by Richard Kettlewell in 69198ec9b9b483a45468a16dcf06f7826b049f20 (#175).
