### ISSUE TITLE
Check UINT_MAX in concat

### ISSUE THREAD

**Issue by rra** [InterNetNews/inn#154]
**Reported by iulius on 25 Nov 2016 22:05 UTC**
Homogenize `lib/concat.c` with `tests/tap/basic.c` and `tests/runtests.c` (they differ with the check of `UINT_MAX` and the use of `memcpy()` instead of a loop to concatenate byte by byte the string).

**Comment by Julien-Elie** [comment]
Fixed, now that the check for potential overrun has been added.
No need to optimize how concatenation is done (we're speaking of tiny strings).
