### ISSUE TITLE
Drop obsolete Python and Perl hooks wrappers

### ISSUE THREAD

**Issue by rra** [InterNetNews/inn#163]
**Reported by iulius on 18 Apr 2018 20:20 UTC**
INN provides wrappers in the samples directory for an obsolete use of Python and Perl hooks (for INN versions predating INN 2.4.0).

It is time to drop these samples in INN 2.7.0, as well as references to them in source code and documentation.  Old `nnrppythonauth` and `nnrpperlauth` `inn.conf` references should also be dropped.

**Comment by Julien-Elie** [comment]
Done in 1cc7230abe46e75546581cc874a95c7c84afc398.
