### ISSUE TITLE
Unable to start inn2 version 2.6.4-2 on debian bullseye status=238/STATE_DIRECTORY

### ISSUE THREAD

**Issue by sfdp** [InterNetNews/inn#235]
Unable to start inn2 version 2.6.4-2 on debian bullseye

permission on /var/lib/private is 700

systemctl start inn2.service
Job for inn2.service failed because the control process exited with error code.
See "systemctl status inn2.service" and "journalctl -xe" for details.

systemctl status inn2.service
● inn2.service - InterNetNews
     Loaded: loaded (/lib/systemd/system/inn2.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2022-05-13 15:28:34 PDT; 18s ago
       Docs: man:innd(8)
    Process: 3284 ExecStart=/usr/lib/news/bin/rc.news (code=exited, status=238/STATE_DIRECTORY)
   Main PID: 3284 (code=exited, status=238/STATE_DIRECTORY)
        CPU: 1ms

May 13 15:28:34 usenet-dev.stanford.edu systemd[1]: Starting InterNetNews...
May 13 15:28:34 usenet-dev.stanford.edu systemd[3284]: inn2.service: Failed to set up special execution directory in /var/lib: Not a directory
May 13 15:28:34 usenet-dev.stanford.edu systemd[3284]: inn2.service: Failed at step STATE_DIRECTORY spawning /usr/lib/news/bin/rc.news: Not a directory
May 13 15:28:34 usenet-dev.stanford.edu systemd[1]: inn2.service: Main process exited, code=exited, status=238/STATE_DIRECTORY
May 13 15:28:34 usenet-dev.stanford.edu systemd[1]: inn2.service: Failed with result 'exit-code'.
May 13 15:28:34 usenet-dev.stanford.edu systemd[1]: Failed to start InterNetNews.

**Comment by Julien-Elie** [comment]
`inn2.service: Failed to set up special execution directory in /var/lib: Not a directory`

Where is `/var/lib` referenced in your _inn2.service_ file, and what files related to INN are located in that directory?

The default _inn2.service_ file shipped with Debian does not reference it, and I don't see any files installed in _/var/lib_ in the default installation.

**Comment by Julien-Elie** [comment]
Reported in https://bugs.debian.org/1011103
```
In any event I have found the issue. As you can see from the above 
/var/lib/news is a symbolic link. In the service file StateDirectory is 
set to news which resolves to /var/lib/news. It seems that systemd does 
not like StateDirectory to be a symbolic link. Lesson learned.
```
