### ISSUE TITLE
Is [abc^] a valid uwildmat expression?

### ISSUE THREAD

**Issue by denizdogan** [InterNetNews/inn#259]
I've been trying to figure out this mini-language lately. Maybe the ambiguity of this is intentional, or maybe it's explicitly not defined, or maybe the answer is just "YES!"

`[^abc]` would match anything that is _not_ a, b, or c.

1. Would `[abc^]` match anything that is a, b, c, or  ^?
2. If yes, is it also intentional and explicitly part of the uwildmat specification?
3. If no, would it be considered a syntax error, or some other error?

Many thanks!

**Comment by Julien-Elie** [comment]
Yes, `[abc^]` is valid and matches these 4 characters.
It is the usual wildmat behaviour, and explicitly part of the [uwildmat specification](https://www.eyrie.org/~eagle/software/inn/docs/libinn-uwildmat.html).

You could create a `test` file, and try `grep` on it:

```
% cat test        
^
^a
^b
% grep '[^^]' test
^a
^b
grep '[a^]' test
^
^a
^b
```

`[^^]` excludes the line with only that excluded `^` char; `[a^]` shows all lines with either `a` or `^`.
uwildcat does not change that.

**Comment by denizdogan** [comment]
@Julien-Elie Thank you for answering! Closing this.
