### ISSUE TITLE
inncheck error

### ISSUE THREAD

**Issue by nelgin** [InterNetNews/inn#268]
Using the recommended parameters per the man page

news@www:~/bin$ inncheck -a --perm --pedantic

Results in the following error.

Use of uninitialized value $k in hash element at /news/bin/inncheck line 834, <$IN> line 325.
/news/etc/newsfeeds:319: unknown flag `'

**Comment by nelgin** [comment]
It was bad information from a new peer

  :Ap,Tm,,<262144:innfeed!

Looks like it didn’t like the double comma. I removed it and did a new check and the error is gone. Might be worth catching it though.

**Comment by Julien-Elie** [comment]
Fixed.  There's no longer a Perl warning for an undefined variable.  And the reported error will now be:

```
/news/etc/newsfeeds:319: empty flag in `Ap,Tm,,<262144'
```

It will be easier to understand what is wrong.
