### ISSUE TITLE
Packaging INN for NixOS

### ISSUE THREAD

**Issue by ne9z** [InterNetNews/inn#278]
Hello, just recently discovered Usenet as an open, free-as-in-freedom way to retrieve and publish textual information.  I was born in the year 2000 and I'm just twenty years' late!  I'm using Emacs/Gnus as my newsreader and using [gwene unidirectional RSS-to-NNTP](http://gwene.org/) and [gmane.io bidirectional mailing-list-to-NNTP](https://gmane.io/) service.
![gnus](https://github.com/InterNetNews/inn/assets/77314501/88e4311e-fb01-4acb-85c5-5802019af6d8)

I would like to self-host INN with my GNU/Linux distribution of choice, which is NixOS.  INN is currently not packaged for NixOS and I would like to do so.  It mainly involves two steps:

- Package INN and its dependencies, which I have done in [this pull request](https://github.com/NixOS/nixpkgs/pull/248320), mostly by following [the installation guide](https://www.eyrie.org/~eagle/software/inn/docs-2.7/install.html).  Please [suggest changes](https://github.com/NixOS/nixpkgs/pull/248320/files) in the pull request, as I am totally new to INN.
- Create a new configuration module for INN.  This allows users to configure INN via the Nix interface alone, instead of editing many configuration files.  An example would be the [Nginx module](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/web-servers/nginx/default.nix).  So where can I find a complete reference of all INN options?

Regards,
Maurice

**Comment by Julien-Elie** [comment]
Hi Maurice,
Thanks for helping in packaging INN on more distributions!
I've had a look at your suggested script for NixOS packaging.  It seems good to me.  FWIW, if not already done, you can see what [FreeBSD](https://cgit.freebsd.org/ports/tree/news/inn), [Debian](https://salsa.debian.org/md/inn2/-/tree/master/debian), [Fedora](https://src.fedoraproject.org/rpms/inn/tree/rawhide) or [Arch Linux](https://gitlab.archlinux.org/archlinux/packaging/packages/inn) are doing, amongst other distributions.
Be sure that the installed package is ready for use (_history_ file created, right permissions, crontab with `news.daily` and a daily flush of _incoming.conf_ as explained in the installation guide).

As for the configuration module as a GUI, that's a tough work as INN has many configuration files.  The complete reference is [the manual pages of each configuration file](https://www.eyrie.org/~eagle/software/inn/docs/)!

Do not hesitate to post any question you would have about configuration files in the news.software.nntp newsgroup, where you'll probably receive quick answers.

**Comment by ne9z** [comment]
Thanks for the pointer to the manual pages, there's indeed quite a few options, thankfully each of them are documented in detail.  I'll try to cover basic use-cases first.
