### ISSUE TITLE
Remove or fix installation of signcontrol

### ISSUE THREAD

**Issue by rra** [InterNetNews/inn#28]
**Reported by eagle on 14 Dec 2008 05:29 UTC**
signcontrol is currently unconditionally installed even though it has per-site configuration, so that configuration would be overwritten on make update.

It's not clear that INN should be shipping this program at all.  Only a few people will need to issue PGP-signed control messages, and those who do can easily get it as part of the pgpverify distribution (or download one of the many other programs for this purpose).

**Comment by rra** [comment]
**Comment by iulius on 11 Jul 2011 12:37 UTC**
In order to prevent replay of old control articles, the Injection-Date: header field should be added to @signheaders and @orderheaders (and also be computed as the Date: header field).

**Comment by Julien-Elie** [comment]
I'll move **signcontrol** to the _contrib_ directory for 2.7.0.
This way, it will no longer be installed by default and overwritten during a `make update`.

Feel free to comment if you think another action should be done.

**Comment by Julien-Elie** [comment]
> **Comment by iulius on 11 Jul 2011 12:37 UTC**
> In order to prevent replay of old control articles, the Injection-Date: header field should be added to @signheaders and @orderheaders (and also be computed as the Date: header field).

Patches submitted upstream.

**Comment by Julien-Elie** [comment]
> I'll move **signcontrol** to the _contrib_ directory for 2.7.0. This way, it will no longer be installed by default and overwritten during a `make update`.
> 
> Feel free to comment if you think another action should be done.

Let's remove it from the INN distribution, after a discussion in _inn-workers_.
