### ISSUE TITLE
Support GnuTLS for nnrpd TLS support

### ISSUE THREAD

**Issue by rra** [InterNetNews/inn#30]
**Reported by eagle on 14 Dec 2008 05:37 UTC**
GnuTLS has a nicer API and a very active upstream, as well as a nicer license for some purposes.  It would be nice to support either TLS library in nnrpd (which would probably require refactoring the TLS code extensively so that we could support multiple underlying layers, since the OpenSSL compatibility code in GnuTLS is probably not up to the task).

**Comment by Julien-Elie** [comment]
More than a decade later, OpenSSL has a nicer API (especially in its latest 3.0.0 release, already supported by INN) and is wide-spread.
I am unsure it is still worthwhile trying to support several external TLS libraries.  I therefore suggest to close this ticket.  Any thoughts or complaints about that?

Should we try to support LibreSSL and BoringSSL though?  (derivates from OpenSSL, so probably easier to integrate -- I've not checked)

**Comment by Julien-Elie** [comment]
Also note that, starting from its 3.0.0 release, OpenSSL is under the Apache License v2 (and no longer under the special OpenSSL and SSLeay licenses).

**Comment by rra** [comment]
I agree, I don't think this is worth supporting now. For a while it looked like GnuTLS may be a viable competitor to OpenSSL, but the world has converged on OpenSSL again, maintenance has improved, the licensing has improved, and GnuTLS tends to have a lot of interoperability problems.  I think only supporting OpenSSL is fine.
