### ISSUE TITLE
How the global hierarchy can work?

### ISSUE THREAD

**Issue by korpe1** [InterNetNews/inn#304]
How the global hierarchy can works?

Is it right, that the USENET itself is just a bunch of files in certain format? For example, I have this INN running on my server that manages `/var/spool/news/` directory which contain `/var/spool/news/comp/os/linux`, `/var/spool/news/alt/tv/simpsons` etc. and then feed it through NNTP, UUCP or any other way (even physically disk) to peer servers? So it's just files in structure that peers feeds among themselves?

Okay, there we have The Big 8 naming convention to the directories or newsgroups (hierarchy), but admins don't have to implement that, right? Then what happens if I setup own NTTP server and start own comp.* hierarchy of newsgroups and feeding it to other the public NTTP servers that follow The Big 8? What happens in that conflict situation? Or are names of newsgroups something like DNS that The Big 8 can "own"?

Can I make a new newsgroup in INN just with command "mkdir /var/spool/news/myowngroup/"?

**Comment by korpe1** [comment]
@Julien-Elie: Sorry, I tag you cause it seems that nearly no one devs here in the GitHub (maybe them use just Git+email?).

**Comment by Julien-Elie** [comment]
To create a newsgroup in INN, you can just type `ctlinnd newgroup my.own.group` (see the manual page of **ctlinnd** for more information).  When posting a message to this newsgroup, INN will automatically create the directory `/var/spool/news/my/own/group/` and store the articles there, assuming you're using the `tradspool` storage method (see the manual page of _storage.conf_ for more information).  Other storage methods exist, and they'll store articles in other kinds of format.

To respond to your other question, creating by hand a comp.local newsgroup will just create it on your news server.  Other news servers won't have it.  Usually, if you send articles to this newsgroup, they will just be rejected by other servers as they do not carry the additional comp.local newsgroup you have manually added on your own news server.

**Comment by korpe1** [comment]
> To create a newsgroup in INN, you can just type ctlinnd newgroup my.own.group (see the manual page of ctlinnd for more information). When posting a message to this newsgroup, INN will automatically create the directory /var/spool/news/my/own/group/ and store the articles there, assuming you're using the tradspool storage method (see the manual page of storage.conf for more information). Other storage methods exist, and they'll store articles in other kinds of format.

I read that `ctlinnd newgroup` command basically just make a standard usenet control message, but what the server concretely does when it get one? If I just manually make new directory and add it to the `active` conf file, does it work?

>> Then what happens if I setup own NTTP server and start own comp.* hierarchy of newsgroups and feeding it to other the public NTTP servers that follow The Big 8? What happens in that conflict situation?
>
> To respond to your other question, creating by hand a comp.local newsgroup will just create it on your news server. Other news servers won't have it. Usually, if you send articles to this newsgroup, they will just be rejected by other servers as they do not carry the additional comp.local newsgroup you have manually added on your own news server.

Okay, but what if my own comp.* group is e.g. comp.os.minix or something other common. In this situation my server and they others have own groups with exactly the same names. What happens in this conflict situation?

Also: 
Okay, there we have The Big 8 naming convention to the directories or newsgroups (hierarchy), but admins don't have to implement that, right? Or are names of newsgroups something like DNS that The Big 8 can "own"?

**Comment by Julien-Elie** [comment]
> If I just manually make new directory and add it to the `active` conf file, does it work?

Yes, it would work.  Be sure to pause INN before modifying its _active_ file (`ctlinnd pause reason` command).  This is not the recommended method because of possible mistakes when editing the file.  Creating the directory is not necessary (INN will create it when receiving the first article.)


> Okay, but what if my own comp.* group is e.g. comp.os.minix or something other common. In this situation my server and they others have own groups with exactly the same names. What happens in this conflict situation?

If comp.os.minix exists on other servers, the articles you post to this newsgroup and send to your peers will just show up in the servers carrying a newsgroup with the same name.
Similarly, articles you receive from your peers for this newsgroup will also show up in yours.

Anyway, when you have local newsgroups, you normally do not send their articles to your peers so this conflict situation should not occur.  In your _newsfeeds_ file, you would add "@comp.os.minix" at the end of the newsgroups pattern you send.


> Also: Okay, there we have The Big 8 naming convention to the directories or newsgroups (hierarchy), but admins don't have to implement that, right? Or are names of newsgroups something like DNS that The Big 8 can "own"?

Your server, your rules.  Admins are not obliged to carry any newsgroups.  There's no authoritative servers like DNS root servers.  The Big-8 owns nothing, they just monthly publish a list of "official" newsgroups signed with a PGP key (this is what is called a checkgroups control article).  A news admin is not obliged to process these articles neither create the same exact list in his news server.

**Comment by pmetzger** [comment]
This doesn't seem to be a bug report?

**Comment by Julien-Elie** [comment]
Indeed.  We sometimes have issues which are not a bug report.  Each time it happens, I wondered whether we should not create a dedicated label to mark them.  Now done, I have just created a [question](https://github.com/InterNetNews/inn/issues?q=label%3Aquestion) label.

While I was at it, I also created a [test suite](https://github.com/InterNetNews/inn/issues?q=label%3A%22C%3A+test+suite%22) label and a [stalled](https://github.com/InterNetNews/inn/issues?q=label%3Astalled) label as I also noticed they are useful for triage.

**Comment by korpe1** [comment]
Thank you for all your answers, them were pretty helpfully! The last questions: 

Is it right to describe newsgroups as just tags for articles and not "places"? I mean it's pretty common to say that something was posted on Usenet in e.g. comp.os.minix, but basically that comp.os.minix is just tag convention that most of news servers honour.

> they just monthly publish a list of "official" newsgroups signed with a PGP key (this is what is called a checkgroups control article).

Can you tell me a little more about that list which is signed with PGP? Or refer to articles/docs about it?

Thank you once again :)

**Comment by pmetzger** [comment]
> Indeed. We sometimes have issues which are not a bug report.

This is what [github discussions](https://docs.github.com/en/discussions) are for. You turn that on and you get a automatic support forum with very little effort.

**Comment by Julien-Elie** [comment]
> Is it right to describe newsgroups as just tags for articles and not "places"? I mean it's pretty common to say that something was posted on Usenet in e.g. comp.os.minix, but basically that comp.os.minix is just tag convention that most of news servers honour.

You can consider a newsgroup as a (readable) name, an identifier, a place, a tag, etc.
An article, defined by its unique Message-ID, belongs to one or more newsgroups.  I don't understand well your point about tags.
Anyway, I would suggest that further discussions take place on Usenet 😄  for instance on the `news.misc` newsgroup.


> Can you tell me a little more about that list which is signed with PGP? Or refer to articles/docs about it?

It is what is called a checkgroups.  More information: https://www.big-8.org/wiki/Checkgroups
