### ISSUE TITLE
filter_innd.py and python-3.12.7 compatibility

### ISSUE THREAD

**Issue by G4tty0** [InterNetNews/inn#314]
After a year of release, I upgraded python to the version 3.12.7, recompiled the software to the version inn-2.8.20241006, everything is fine, however I get some messages from errlog:

"""
/usr/inn/filter/filter_innd.py:121: SyntaxWarning: invalid escape sequence '\s'
  self.re_newrmgroup = re.compile("(?:new|rm)group\s")
/usr/inn/filter/filter_innd.py:124: SyntaxWarning: invalid escape sequence '\d'
  self.re_none44 = re.compile("none\d+\.yet>")
/usr/inn/filter/filter_innd.py:126: SyntaxWarning: invalid escape sequence '\!'
  self.re_meow = re.compile("^Meow\!", re.M)
"""

I solved it like this prototype:

"""
import re
re.compile(r"(?:new|rm)group\s")
re.compile(r"none\d+\.yet>")
re.compile(r"^Meow\!", re.M)
"""

I had written an usenet article but Nigel Reed I ask me to open a issues on GitHUB... it has been done!

**Comment by Julien-Elie** [comment]
Thanks for the bug report!
There was indeed a language change in Python 3.12:
  https://docs.python.org/3.12/whatsnew/3.12.html

> A backslash-character pair that is not a valid escape sequence now generates a `SyntaxWarning`, instead of `DeprecationWarning`.  For example, `re.compile("\d+\.\d+")` now emits a `SyntaxWarning` ("\d" is an invalid escape sequence, use raw strings for regular expression: `re.compile(r"\d+\.\d+")`).

I'll update the sample _filter_innd.py_ script to fix this warning.  Raw strings also exist in Python 2 so the fix works for both versions.
