### ISSUE TITLE
Support storing filtered articles instead of rejecting them

### ISSUE THREAD

**Issue by rra** [InterNetNews/inn#38]
**Reported by eagle on 14 Dec 2008 06:21 UTC**
This patch from Christoph Biedl <cbiedl@gmx.de> allows one to store filtered articles into a separate storage class instead of just rejecting them (allowing one's spam filtering rules to be reviewed, for example).

- [store-filtered.diff.txt](https://github.com/InterNetNews/inn/files/6835435/store-filtered.diff.txt)
- [log-filtered.patch.txt](https://github.com/InterNetNews/inn/files/6835436/log-filtered.patch.txt) (Follow-on to improve logging and outgoing feeds)

**Comment by rra** [comment]
**Modified by iulius on 11 Nov 2016 14:46 UTC**

**Comment by Julien-Elie** [comment]
[log-filtered.patch.txt](https://github.com/InterNetNews/inn/files/6835436/log-filtered.patch.txt) was totally integrated in INN 2.5.0 in 2009 (e557092c85ee0c39173b1742afa755386caa025d) as well as the part of [store-filtered.diff.txt](https://github.com/InterNetNews/inn/files/6835435/store-filtered.diff.txt) about logging to _news.notice_ (b89861be896c20f92bdc3be9babf27ed8f59f4a0)

An up-to-date patch for the remaining changes in [store-filtered.diff.txt](https://github.com/InterNetNews/inn/files/6835435/store-filtered.diff.txt) against STABLE IN 2.7.2 has just been provided by Christoph on inn-workers.  It's now time to finalize its integration!
